# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotmpl < Formula
  desc "Gotmpl is a command line tool to generate files from template and data files"
  homepage ""
  version "1.0.0"
  license "MIT"

  depends_on "go" => :optional
  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hay-kot/gotmpl/releases/download/v1.0.0/gotmpl_Darwin_arm64.tar.gz"
      sha256 "34104b91fd096f2360ff5710babf199d1620db3b1791af493f039092a98f945a"

      def install
        bin.install "gotmpl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/gotmpl/releases/download/v1.0.0/gotmpl_Darwin_x86_64.tar.gz"
      sha256 "b1dcbb7f0cd826000dd6e3fb1da5b992fad3d077a2cdacc688d0f24a6c009d9e"

      def install
        bin.install "gotmpl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/gotmpl/releases/download/v1.0.0/gotmpl_Linux_x86_64.tar.gz"
      sha256 "c8b856fc0672838effabbd261eb618e813a319ff1655ce3d37c1964f6db14e5d"

      def install
        bin.install "gotmpl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hay-kot/gotmpl/releases/download/v1.0.0/gotmpl_Linux_arm64.tar.gz"
      sha256 "86fe76ed06c09852a8306a04bb1ceafe924433c60ab9536524d5f06e13a8e5c5"

      def install
        bin.install "gotmpl"
      end
    end
  end

  test do
    system "#{bin}/gotmpl version"
  end
end
